# Use an official Amazon Linux 2 image as the base
FROM amazonlinux:2

# Install dependencies
RUN yum install -y python3 python3-pip

# Set the working directory to /app
WORKDIR /app

# Copy the requirements file
COPY requirements.txt .

# Install the dependencies
RUN pip3 install --no-cache-dir -r requirements.txt

# Copy the application code
COPY . .

ENV SECRET_KEY
# Collect static files
RUN python3 manage.py collectstatic --no-input

# Expose the port
EXPOSE 8000

# Run the command to start the development server
CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"]



