# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file
COPY requirements.txt .

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Install the tk-dev package
RUN apt-get update && apt-get install -y tk-dev

# Install the libtcl8.6 and libtk8.6 packages
RUN apt-get install -y libtcl8.6 libtk8.6

# Copy the application code
COPY . .

ENV SECRET_KEY=django-insecure-%#glg4fdwzoh_u2e9-wkwli45+&m!foy3su7lm5zxohibah2#^

# Collect static files
RUN python manage.py collectstatic --no-input

# Expose the port the application will run on
EXPOSE 80

# Run the command to start the application
CMD ["python", "manage.py", "runserver", "0.0.0.0:80"]


